[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "piphawk_ai"
version = "0.5.0"
requires-python = ">=3.11"

[tool.setuptools]
packages = ["piphawk_ai"]
