volatility_levels:
  low:
    adx_m5_min: 22
    atr_pct_m5_min: 0.003
    adx_m1_min: 18
    atr_pct_m1_min: 0.002
  normal:
    adx_m5_min: 25
    atr_pct_m5_min: 0.004
    adx_m1_min: 20
    atr_pct_m1_min: 0.0025
  high:
    adx_m5_min: 28
    atr_pct_m5_min: 0.005
    adx_m1_min: 22
    atr_pct_m1_min: 0.003
scalp:
  adx_m5_max: 15
  atr_pct_m5_max: 0.0025
  adx_m1_max: 12
  body_shrink_ratio: 0.35
  s10_adx_min: 20
  s10_atr_pct_min: 0.001
weights:
  adx_m5: 3
  atr_pct_m5: 1
  adx_m1: 2
  atr_pct_m1: 1
  ema_slope_base: 2
  ema_slope_strong: 3
hysteresis:
  trend: 3
  scalp: 3
  strong_trend: 2
trend_score_min: 3
scalp_score_max: -1
ema_slope:
  mild: 0.05
  strong: 0.15
