SCALP_MODE: true
ENABLE_RANGE_ENTRY: true
BAND_WIDTH_THRESH_PIPS: 0
SCALP_ADX_MIN: 15  # エントリー頻度を上げるため閾値を下げる
BYPASS_PULLBACK_ADX_MIN: 20  # プルバック待ちを減らす
AI_COOLDOWN_SEC_FLAT: 15
SCALP_SUPPRESS_ADX_MAX: 60
SCALP_TP_PIPS: 4
SCALP_SL_PIPS: 4
SCALP_COND_TF: S10
TREND_COND_TF: M5
SCALP_OVERRIDE_RANGE: false
MIN_RRR: 1.0
ENFORCE_RRR: false
MIN_HOLD_SECONDS: 300
SCALP_PROMPT_BIAS: aggressive  # AIにより積極的な判断を促す
