risk:
  min_atr_sl_multiplier: 1.2
  min_rr_ratio: 1.2
filters:
  avoid_false_break:
    lookback_candles: 20
    threshold_ratio: 0.2
reentry:
  enable: true
  trigger_pips_over_break: 1.5
ADX_SCALP_MIN: 15
SCALP_SUPPRESS_ADX_MAX: 70
SCALP_TP_PIPS: 8
SCALP_SL_PIPS: 8
SCALP_PROMPT_BIAS: aggressive

fallback:
  force_on_no_side: true
  default_sl_pips: 12
  default_tp_pips: 18
  dynamic_risk: false

order:
  max_spread_pips: 2.0
  price_bound_pips: 3.0
