risk:
  min_atr_sl_multiplier: 1.2
  min_rr_ratio: 1.2
filters:
  avoid_false_break:
    lookback_candles: 20
    threshold_ratio: 0.2
reentry:
  enable: true
  trigger_pips_over_break: 1.5
SCALP_MODE: false
SCALP_ADX_MIN: 45
SCALP_TP_PIPS: 5
SCALP_SL_PIPS: 3
