name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps & run pytest
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          # PyTorch の CPU ホイールを取得するために専用インデックスを追加
          pip install --extra-index-url https://download.pytorch.org/whl/cpu -r backend/requirements.txt
          # テストに必要な追加依存もインストール
          pip install -r backend/requirements-dev.txt
          pip install -r requirements-dev.txt
          pytest -q

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/piphawk:latest
            ghcr.io/${{ github.repository_owner }}/piphawk:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SSH & deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/piphawk
            docker pull ghcr.io/${{ github.repository_owner }}/piphawk:latest
            docker rm -f piphawk-app || true
            docker run -d \
              --name piphawk-app \
              --restart unless-stopped \
              -v /opt/piphawk/backend/logs:/app/backend/logs \
              -v /opt/piphawk/data/trades.db:/app/trades.db \
              ghcr.io/${{ github.repository_owner }}/piphawk:latest
