name: Optuna-Filter-Search

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        trial: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install optuna PyYAML
          pip install -r requirements-dev.txt
      - name: Run optimization
        run: |
          python optuna/bayes_filter_opt.py
      - name: Create PR for results
        uses: peter-evans/create-pull-request@v6
        with:
          branch: optuna-results
          title: 'Update best_filters.yaml'
          commit-message: 'chore: update best_filters.yaml'
          reviewers: reviewer1,reviewer2
