name: RL-Offine-Training

on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  train:
    runs-on: [self-hosted, trainer]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements-test.txt

      - name: Run offline RL training
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
          PG_DSN: ${{ secrets.PG_DSN }}
        run: |
          python rl/train_offline.py --redis-url "$REDIS_URL" --pg-dsn "$PG_DSN" --outdir models/rl/latest

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: rl-model
          path: models/rl/latest
